version: "2"
services:

  web:
    image: rp2017-front-2-ruhm
    container_name: "reactApp"
    networks:
      - main
    build: .
    ports:
      - "3446:3446"
    volumes:
      - .:/var/www/rp2017-front-2-ruhm/
      - /var/www/rp2017-front-2-ruhm/node_modules
    command: npm run dev

  nginx:
    image: nginx
    container_name: "nginx"
    depends_on:
      - web
    networks:
      - main
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  main:
    external: 
      name: rp2017algus2ruhm_main
